In [6]:
import numpy as np
import pandas as pd
import pickle

import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD
from sklearn import preprocessing

In [2]:
df = pd.read_csv('score.csv', header=None)

# ダミーデータ生成
DATA_LEN = 10
X_LEN = 5

import numpy as np
x_train = np.random.random((DATA_LEN, X_LEN))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(DATA_LEN, 1)), num_classes=10)
x_test = np.random.random((DATA_LEN, X_LEN))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(DATA_LEN, 1)), num_classes=10)

model = Sequential()
# Dense(64) は，64個のhidden unitを持つ全結合層です．
# 最初のlayerでは，想定する入力データshapeを指定する必要があり，ここでは20次元としてます．
model.add(Dense(64, activation='relu', input_dim=X_LEN))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

# model.fit(x_train, y_train,
#           epochs=20,
#           batch_size=128)
# score = model.evaluate(x_test, y_test, batch_size=128)

In [7]:
pd.get_dummies(y)

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
5,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206595,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206600,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
206601,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
206607,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206611,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
x = df[df[13] == 3].iloc[:, 9:12]
y = df[df[13] == 3].iloc[:, 12]

model = Sequential()
# Dense(64) は，64個のhidden unitを持つ全結合層です．
# 最初のlayerでは，想定する入力データshapeを指定する必要があり，ここでは20次元としてます．
model.add(Dense(64, activation='relu', input_dim=3))
model.add(Dropout(0.1))
# model.add(Dense(64, activation='relu'))
# model.add(Dropout(0.1))
model.add(Dense(24, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

history = model.fit(x.values, pd.get_dummies(y).values,epochs=20,batch_size=128)
# score = model.evaluate(x_test, y_test, batch_size=128)

Epoch 1/20
336/336 [==============================] - 0s 1ms/step - loss: 2.4898 - accuracy: 0.2769
Epoch 2/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1799 - accuracy: 0.3498
Epoch 3/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1547 - accuracy: 0.3609
Epoch 4/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1452 - accuracy: 0.3660
Epoch 5/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1338 - accuracy: 0.3680
Epoch 6/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1285 - accuracy: 0.3692
Epoch 7/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1210 - accuracy: 0.3735
Epoch 8/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1179 - accuracy: 0.3740
Epoch 9/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1153 - accuracy: 0.3750
Epoch 10/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1093 - accuracy: 0.3769
Epoch 11/20
336/336 [==============================] - 1s 2ms/step - loss: 2.1100 - accuracy: 0.3768
Epoch 12/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1056 - accuracy: 0.3771
Epoch 13/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1060 - accuracy: 0.3778
Epoch 14/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1032 - accuracy: 0.3777
Epoch 15/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1002 - accuracy: 0.3769
Epoch 16/20
336/336 [==============================] - 0s 1ms/step - loss: 2.1010 - accuracy: 0.3795
Epoch 17/20
336/336 [==============================] - 1s 2ms/step - loss: 2.0990 - accuracy: 0.3811
Epoch 18/20
336/336 [==============================] - 0s 1ms/step - loss: 2.0978 - accuracy: 0.3821
Epoch 19/20
336/336 [==============================] - 1s 2ms/step - loss: 2.0948 - accuracy: 0.3822
Epoch 20/20
336/336 [==============================] - 1s 2ms/step - loss: 2.0949 - accuracy: 0.3815

In [10]:
x

          9     10    11
5       1.47  0.95  2.26
13      1.83  2.47  3.46
19      0.41  1.14  0.73
20      0.41  1.72  0.15
27     -0.70 -1.69 -2.05
...      ...   ...   ...
206595 -0.78 -0.69 -2.09
206600 -2.36 -0.83 -0.53
206601 -3.62 -2.09 -3.05
206607 -2.40  0.80 -0.40
206611  0.53  2.52  1.23

[42946 rows x 3 columns]

In [4]:
model.predict([[1,2,1]])

array([[0.03950056, 0.3690158 , 0.0254701 , 0.19339176, 0.01840753,
        0.03956622, 0.00551706, 0.07712913, 0.00880085, 0.13663113,
        0.00627143, 0.01855219, 0.00130022, 0.01603711, 0.00209036,
        0.01043967, 0.00458167, 0.00173884, 0.00304966, 0.00615556,
        0.00234667, 0.00599363, 0.00474225, 0.00327057]], dtype=float32)

In [5]:
x.values

array([[ 1.47,  0.95,  2.26],
       [ 1.83,  2.47,  3.46],
       [ 0.41,  1.14,  0.73],
       ...,
       [-3.62, -2.09, -3.05],
       [-2.4 ,  0.8 , -0.4 ],
       [ 0.53,  2.52,  1.23]])

In [6]:
y.values

array([ 2,  0,  9, ..., 21, 13,  7])